from collections import defaultdict
from enum import Enum, auto
import os
import re
from typing import Any, ClassVar, Literal, get_args

from bokeh.document import Document
from bokeh.embed import components
from bokeh.events import DocumentReady
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.models.dom import DOMElement
import pydantic


JsType = Literal["number", "string", "boolean", "object", "array", "date", "bigint", "symbol", "function", "undefined", "null", "map", "set"]  # fmt: skip
_JS_TYPES: frozenset[str] = frozenset(get_args(JsType))

CdsFlowColumnSpec = tuple[str, list[Any]]


class InputType(Enum):
    SingleValue = auto()
    Array = auto()


class CdsFlowColumn(pydantic.BaseModel):
    name: str
    js_type: JsType
    initial_value: list = []
    input_type: InputType = InputType.Array


class LinkedCdsFlowColumn(pydantic.BaseModel):
    cds_flow_column: CdsFlowColumn
    cds_flow_name: str

    @property
    def js_attr_name(self) -> str:
        return f"{self.cds_flow_name}_{self.cds_flow_column.name}"

    @property
    def js_attr_type(self) -> str:
        if self.cds_flow_column.input_type == InputType.SingleValue:
            return self.cds_flow_column.js_type
        else:
            return f"{self.cds_flow_column.js_type}[]"

    @property
    def js_input(self) -> str:
        if self.cds_flow_column.input_type == InputType.SingleValue:
            return f"{self.cds_flow_name}.data.{self.cds_flow_column.name}[0]"
        else:
            return f"[... {self.cds_flow_name}.data.{self.cds_flow_column.name}]"


class CdsFlow:
    def __init__(
        self,
        name: str,
        columns: list[CdsFlowColumn],
        depends_on_columns: list[LinkedCdsFlowColumn] | None = None,
    ):
        if depends_on_columns is None:
            depends_on_columns = []
        self.name = name
        if columns:
            if len({col.input_type for col in columns}) > 1:
                raise ValueError(f"Different input types found for {self.name}. {self.columns!r}")
        self._base_columns = columns
        self.source = ColumnDataSource({column.name: column.initial_value for column in columns})
        self.depends_on_columns = depends_on_columns

    @property
    def columns(self) -> dict[str, LinkedCdsFlowColumn]:
        if not hasattr(self, "_base_columns"):
            return {}
        return {base_column.name: LinkedCdsFlowColumn(cds_flow_column=base_column, cds_flow_name=self.name) for base_column in self._base_columns}

    @property
    def dependencies(self) -> set[str]:
        return {depends_on_column.cds_flow_name for depends_on_column in self.depends_on_columns}

    @property
    def callback_name(self) -> str:
        return f"update_{self.name}"

    def callback_location(self, file_dir: str) -> str:
        return os.path.join(file_dir, f"{self.name}.js")

    def _update_signature(self, file_dir: str) -> None:
        START_MARKER = "// === AUTOGENERATED START ==="
        END_MARKER = "// === AUTOGENERATED END ==="

        if len(self.dependencies) == 0:
            return

        js_path = self.callback_location(file_dir)
        if not os.path.exists(js_path):
            with open(js_path, "w") as f:
                f.write(f"{START_MARKER}\n")
                f.write(f"{END_MARKER}\n")
                f.write(f"  console.log('Running function {self.callback_name}');\n")
                f.write(f"""  return {{{", ".join(f"'{col}': this_{col}" for col in self.columns)}}}\n""")
                f.write("}\n")

        with open(js_path, "r+") as f:
            contents = f.read()
            if START_MARKER not in contents or END_MARKER not in contents:
                raise ValueError(f"File '{js_path}' is missing start or end marker")

            start_idx = contents.index(START_MARKER) + len(START_MARKER)
            end_idx = contents.index(END_MARKER)

            jsdoc_lines = [f" * @param {{{col.js_attr_type}}} this_{col.cds_flow_column.name}" for col in self.columns.values()]
            jsdoc_lines += [f" * @param {{{linked_col.js_attr_type}}} {linked_col.js_attr_name}" for linked_col in self.depends_on_columns]

            params = [f"this_{col.name}" for col in self._base_columns] + [linked_col.js_attr_name for linked_col in self.depends_on_columns]

            if self._base_columns:
                returns_contents = ", ".join(f"{col.cds_flow_column.name}: {col.js_attr_type}" for col in self.columns.values())
                returns_line = f" * @returns {{{{{returns_contents}}}}}"
            else:
                returns_line = " * @returns {{}}"
            jsdoc_text = "/**\n"
            if jsdoc_lines:
                jsdoc_text += "\n".join(jsdoc_lines) + "\n"
            jsdoc_text += returns_line + "\n"
            jsdoc_text += " */\n"
            func_signature = f"function {self.callback_name}({', '.join(params)}) {{\n"

            between_markers = jsdoc_text + func_signature

            new_contents = contents[:start_idx] + "\n" + between_markers + contents[end_idx:]

            f.seek(0)
            f.write(new_contents)
            f.truncate()


class CdsFlowManager:
    def __init__(self, cds_flows: list[CdsFlow], js_dir: str, tick_ms: int, engine_setup: str, engine_code: str):
        if not (isinstance(js_dir, str) and os.path.isdir(js_dir)):
            raise ValueError(f"js_dir '{js_dir}' is not a valid directory")
        self.js_dir = js_dir
        self.cds_flows = {flow.name: flow for flow in cds_flows}
        self.doc = Document()
        self.engine_code = engine_code
        self.engine_setup = engine_setup
        self.tick_ms = tick_ms

    def update_signatures(self):
        for flow in self.cds_flows.values():
            flow._update_signature(self.js_dir)

    def clear_js_files(self):
        response = input(f"Are you sure? This will delete all .js files in {self.js_dir}. Only by entering 'y' will this actually happen.").lower()
        if response != "y":
            return
        for filename in os.listdir(self.js_dir):
            if filename.endswith(".js"):
                file_path = os.path.join(self.js_dir, filename)
                if os.path.isfile(file_path):
                    os.remove(file_path)

    def get_components_and_script(self, dom_elements: dict[str, DOMElement] | None = None) -> tuple[str, dict[str, str]]:
        if dom_elements is None:
            dom_elements = {}
        self.doc = Document()
        self._attach_loop(self.doc)

        new_dom_elements = dict(dom_elements)
        for value in dom_elements.values():
            self.doc.add_root(value)
        for i, flow in enumerate(self.cds_flows.values()):
            new_dom_elements[f"source_{i}"] = flow.source
            self.doc.add_root(flow.source)

        assert set(new_dom_elements.values()) == set(self.doc.roots)

        script, divs = components(new_dom_elements)
        return script, divs

    def _attach_loop(self, doc: Document) -> None:
        self.update_signatures()
        callbacks = "\n"
        for flow in self.cds_flows.values():
            if len(flow.dependencies) > 0:
                with open(flow.callback_location(self.js_dir), "r") as f:
                    cb = f.read()
                callbacks += cb + "\n"

        dirty_requests: defaultdict[str, list[str]] = defaultdict(list)
        for flow in self.cds_flows.values():
            for dependency in flow.dependencies:
                dirty_requests[dependency].append(flow.name)

        unresolved = sorted(self.cds_flows.keys())
        resolved: set[str] = set()
        graph: list[str] = []
        while len(unresolved) > 0:
            for unresolved_name in unresolved:
                unresolved_flow = self.cds_flows[unresolved_name]
                if len(unresolved_flow.dependencies - resolved) == 0:
                    graph.append(unresolved_name)
                    resolved.add(unresolved_name)
                    unresolved.remove(unresolved_name)
                    break
            else:
                raise ValueError(f"Couldn't establish non-circular dependency graph. Resolved: {resolved}. Graph so far: {graph}")

        update_script = ""
        for cds_name in graph:
            flow = self.cds_flows[cds_name]
            reflog_checks = [
                f'refLog["{flow.name}"]["{col.cds_flow_column.name}"] != {flow.name}.data.{col.cds_flow_column.name}' for col in flow.columns.values()
            ]
            update_script += f"""
                // check if need for update
                if (!dirty.includes("{flow.name}")) {{
                    if ({" || ".join(reflog_checks)}) {{
                        dirty.push("{flow.name}");
                    }}
                }}
                if (dirty.includes("{flow.name}")) {{"""
            if len(flow.dependencies) > 0:
                args = [col.js_input for col in list(flow.columns.values()) + flow.depends_on_columns]
                input_type = next(iter(flow.columns.values())).cds_flow_column.input_type
                if input_type == InputType.SingleValue:
                    assignments = [f"'{col.cds_flow_column.name}': [new_data.{col.cds_flow_column.name}]" for col in flow.columns.values()]
                else:
                    assignments = [f"'{col.cds_flow_column.name}': new_data.{col.cds_flow_column.name}" for col in flow.columns.values()]

                update_script += f"""
                    new_data = {flow.callback_name}({", ".join(args)});
                    {flow.name}.data = {{
                        {", ".join(assignments)}
                    }};"""
            if len(dirty_requests[flow.name]) > 0:
                update_script += f"""
                    ["{'","'.join(dirty_requests[flow.name])}"].forEach((dep) => {{if (!dirty.includes(dep) && dep !== "") {{dirty.push(dep)}}}});"""
            update_script += f"""
                    dirty.splice(dirty.indexOf('{flow.name}'), 1);"""

            update_script += f"""
                    {"; ".join(it.replace("!=", "=") for it in reflog_checks)};

                }}
            """

        c = CustomJS(
            args={flow.name: flow.source for flow in self.cds_flows.values()},
            code=f"""
                {callbacks}

                var refLog = {{{",".join(f"'{graph_it}': {{}}" for graph_it in graph)}}};
                var dirty = [];
                var new_data;
                {self.engine_setup}

                function run_update_script() {{
                    {self.engine_code}
                    {update_script}
                }};
                setInterval(run_update_script, {self.tick_ms});
            """,
        )
        doc.js_on_event(DocumentReady, c)


def _normalize_js_type_string(s: str) -> JsType:
    if s in _JS_TYPES:
        return s  # type: ignore[return-value]
    raise TypeError(f"Column js type must be a JsType string, got {s!r}")


def _is_column_spec(val: Any) -> bool:
    if not isinstance(val, tuple) or len(val) != 2:
        return False
    js_t, init = val
    if not isinstance(js_t, str) or not isinstance(init, list):
        return False
    return js_t in _JS_TYPES


class CdsFlowStr(str):
    """Column name as ``str`` for Bokeh, with linkage metadata."""

    linked_column: LinkedCdsFlowColumn
    extra_info: Any

    def __new__(cls, value: str, linked_column: LinkedCdsFlowColumn, extra_info: Any = None, /, **meta: Any):
        obj = str.__new__(cls, value)
        obj.extra_info = extra_info
        for k, v in meta.items():
            setattr(obj, k, v)
        obj.linked_column = linked_column
        return obj

    @classmethod
    def spec(cls, js_type: JsType, initial: list[Any]) -> CdsFlowColumnSpec:
        """Return a column spec tuple; equivalent to ``(js_type, initial)`` with clearer hints."""
        return (js_type, initial)


_CDS_FLOW_RESERVED_NAMES = frozenset(
    {
        "input_type",
        "depends_on_columns",
        "__cds_name__",
        "__module__",
        "__qualname__",
        "__doc__",
        "__annotations__",
        "cds_flow",
        "source",
    }
)


class _CdsFlowMeta(type):
    """Builds a :class:`CdsFlow` from ``(js_type, initial_list)`` column specs and assigns :class:`CdsFlowStr` handles."""

    def __new__(mcs, cls_name: str, bases: tuple[type, ...], namespace: dict[str, Any]) -> type:
        if cls_name == "CdsFlowBase":
            return super().__new__(mcs, cls_name, bases, namespace)
        has_flow_ancestor = CdsFlowBase in bases or any(isinstance(b, type) and issubclass(b, CdsFlowBase) for b in bases)
        if not has_flow_ancestor:
            return super().__new__(mcs, cls_name, bases, namespace)

        input_type = namespace.get("input_type", InputType.Array)
        depends_spec = namespace.get("depends_on_columns", [])

        flow_columns: list[CdsFlowColumn] = []
        column_names: list[str] = []
        for col_name, val in list(namespace.items()):
            if col_name.startswith("_") or col_name in _CDS_FLOW_RESERVED_NAMES:
                continue
            if not _is_column_spec(val):
                continue
            js_raw, init_val = val
            js_type = _normalize_js_type_string(js_raw)
            flow_columns.append(
                CdsFlowColumn(
                    name=col_name,
                    js_type=js_type,
                    initial_value=init_val,
                    input_type=input_type,
                )
            )
            column_names.append(col_name)

        if not flow_columns:
            return super().__new__(mcs, cls_name, bases, namespace)

        cds_name = namespace.get("__cds_name__", re.sub(r"(?<!^)(?=[A-Z])", "_", cls_name).lower())
        linked_deps: list[LinkedCdsFlowColumn] = []
        items: tuple[Any, ...] = depends_spec if isinstance(depends_spec, (list, tuple)) else (depends_spec,)
        for item in items:
            if isinstance(item, type) and getattr(item, "cds_flow", None) is not None:
                linked_deps.extend(item.cds_flow.columns.values())
            elif isinstance(item, CdsFlowStr):
                linked_deps.append(item.linked_column)
            else:
                raise TypeError(f"depends_on_columns entry must be a CdsFlowBase subclass or CdsFlowStr, got {item!r}")

        flow = CdsFlow(cds_name, flow_columns, depends_on_columns=linked_deps)

        for col_name in column_names:
            base_col = next(c for c in flow_columns if c.name == col_name)
            linked = LinkedCdsFlowColumn(cds_flow_column=base_col, cds_flow_name=cds_name)
            namespace[col_name] = CdsFlowStr(
                col_name,
                linked,
                extra_info={"js_type": base_col.js_type, "cds_flow_name": cds_name},
                js_type=base_col.js_type,
                cds_flow_name=cds_name,
            )

        namespace["cds_flow"] = flow
        namespace["source"] = flow.source
        return super().__new__(mcs, cls_name, bases, namespace)


class CdsFlowBase(metaclass=_CdsFlowMeta):
    """Declarative CDS flow row; not instantiable."""

    source: ClassVar[ColumnDataSource]
    cds_flow: ClassVar[CdsFlow]

    def __new__(cls, *args: Any, **kwargs: Any) -> Any:
        raise TypeError(f"{cls.__name__} is declarative only and cannot be instantiated.")
